# Page settings

baseURL = "http://prakharchhipa.in/"
languageCode = "en"
title = "Prakhar Chhipa Resume"
theme = "hugo-devresume-theme"
googleAnalytics = "UA-160598059-1"

publishDir = "docs"



[params]
    author = "Prakhar Chhipa"
    description = "Prakhar Chhipa Resume - Java Backend Resume/CV Template For Software Developers"


    primaryColor = "#54B689"
    textPrimaryColor = "#292929"


    [params.profile]
        enable = true
        name = "Prakhar Chhipa"
        tagline = "Senior Software Engineer"
        avatar = ""


    [params.contact]
        enable = true
        location = "Gurgaon HR India"

        [[params.contact.list]]
        icon = "fas fa-phone-square"
        url = "tel:#"
        text = "+91-82333-66998"
        [[params.contact.list]]
        icon = "fas fa-envelope-square"
        url = "mailto:#"
        text = "prakharchhipa@gmail.com"
        [[params.contact.list]]
        icon = "fas fa-globe"
        url = "#"
        text = "https://prakharchhipa.in"



    [params.skills]
        enable = true

        [[params.skills.list]]
        title = "Technical"
        [[params.skills.list.items]]
        details = "Java | Python | javascript"
        [[params.skills.list.items]]
        details = "Redis | MongoDB | elasticsearch"
        [[params.skills.list.items]]
        details = "PostgreSQL | MySQL"
        [[params.skills.list.items]]
        details = "RabbitMQ | Kafka"
        [[params.skills.list.items]]
        details = "Object-oriented design"
        [[params.skills.list.items]]
           details = "Micro-services architecture"
        [[params.skills.list.items]]
        details = "Design and implement database structures"
        [[params.skills.list.items]]
        details = "Lead and deliver complex software systems"

        [[params.skills.list]]
        title = "Professional"
        [[params.skills.list.items]]
        details = "Effective communication"
        [[params.skills.list.items]]
        details = "Team player"
        [[params.skills.list.items]]
        details = "Strong problem solver"
        [[params.skills.list.items]]
        details = "Good time management"




    [params.education]
        enable = true

        [[params.education.list]]
        degree = "B.Tech. in Computer Science Engineering"
        university = "JEC, Jaipur"
        dates = "2011 - 2015"
        percentage = "78 %"
        [[params.education.list]]
        degree = "Sr Secondary School"
        university = "JNV, Bhilwara"
        dates = "2009"
        percentage = "80 %"





    [params.awards]
        enable = false

        [[params.awards.list]]
        name = "Award Lorem Ipsum"
        body = "Microsoft lorem ipsum"
        date = "2019"
        [[params.awards.list]]
        name = "Award Donec Sodales"
        body = "Oracle Aenean"
        date = "2017"





    [params.languages]
        enable = false

        [[params.languages.list]]
        name = "English"
        level = "Native"
        [[params.languages.list]]
        name = "Spanish"
        level = "Professional"




    [params.interests]
        enable = true

        [[params.interests.list]]
        name = "Photography"
        [[params.interests.list]]
        name = "Football"
        [[params.interests.list]]
        name = "Music"
        [[params.interests.list]]
        name = "Travelling"




    [params.summary]
        enable = true
        text = "5+ years of experience in software development/design in telecom, internet, affiliate, research and digital product base domain."


    [params.experience]
        enable = true

        [[params.experience.list]]
        title = "Senior Software Engineer"
        dates = "May 2018 - Present"
        company = "Airtel X Labs"
        details = "Senior developer having responsibilities of the design, development, and implementation of the back-end applications."
        [[params.experience.list.items]]
        details = "Oversee the efficient use of production project budgets."
        [[params.experience.list.items]]
        details = "Along with development supervise the assessment of various micro-services in order to ensure quality and accuracy of the back-end."

        [[params.experience.list]]
        title = "Full Stack Developer"
        dates = "April 2015 - May 2018"
        company = "91Mobiles"
        details = "Worked as a full stack developer, developed numerous applications(admin panels, websites, crawlers, dashboards, and tools)."


    [params.projects]
        enable = true

        [[params.projects.list]]
        title = "WORK: Field Workforce Management Platform"
        meta = "Airtel X Labs"
        tagline = "Ownership of several micro services, responsible for authentication, authorization, communication(SMS/Email/Notifications), Downstream integrations, approval engine and organization hierarchy. Developed client jar to maintain standard logging across the project."


        [[params.projects.list]]
        title = "Predictive DT: Auto Diagnose Query Resolution Platform"
        meta = "Airtel X Labs"
        tagline = "Developed core backend engine of the application which enables workflow orchestration to solve problem scenarios. Lead predictive DT part, which helped reducing average handling time of calls to 60% at call centers."

        [[params.projects.list]]
        title = "DRIFT: Integration and Transformation Tool"
        meta = "Airtel X Labs"
        tagline = "In a team of 2 people, developed back-end and front-end both for the application. JOLT used to transform the response. Client SDK developed so that any application can plug and play with this tool in the organization."

        [[params.projects.list]]
        title = "Price Comparison Catalog: Product Finder"
        meta = "91Mobiles"
        tagline = "Developed back-end, to handle elasticsearch filter queries dynamically through a panel was the key highlight of this project. Developed a crawling engine using Scrapy to get realtime prices from various websites for this feature."

        [[params.projects.list]]
        title = "Contextual Segmentation: Notification Engine"
        meta = "91Mobiles"
        tagline = "Developed segmentation data resource pipeline as per customer’s interest using user/event tracking data. Owned a panel’s complete development, which is used to target relevant audience using dynamic HTML creation and segmentation data with contextual content using sendgrid and GCM."

        [[params.projects.list]]
        title = "Auto-Suggest: Search Functionality "
        meta = "91Mobiles"
        tagline = "Developed data source for the search engine having 20+ categories and list pages using elasticsearch. Worked in a team of 3 people to build analytics engine on the search events data so that recommendation and relevant search could boost up."


    [params.information]
        enable = false

        [[params.information.list]]
        title = "Papers"
        [[params.information.list.items]]
        details = "2018 · Lorem Ipsum"
        [[params.information.list.items]]
        details = "2016 · Sed Fringilla"

        [[params.information.list]]
        title = "Interests"
        details = "Climbing, Snowboarding, Photography, Travelling"





    [params.social]
        enable = true

        [[params.social.list]]
        icon = "fab fa-github-square"
        url = "//github.com/prakharchhipa"
        title = "prakharchhipa"
        [[params.social.list]]
        icon = "fab fa-linkedin"
        url = "//linkedin.com/in/prakharchhipa"
        title = "prakharchhipa"
        [[params.social.list]]
        icon = "fab fa-twitter-square"
        url = "//twitter.com/prakharchhipa"
        title = "@prakharchhipa"
